title:
  name: Toggl API for golang
  description: "Throttle API for [toggle](https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md)"
user: dougEfresh
project: gtoggl-api
installation: >-
  ```shell

  $ go get -u github.com/kruc/gtoggl-api

  ```
quickStart:
  code: |
    ```go
    import "github.com/kruc/gtoggl"
    import "github.com/kruc/gtoggl-api/gtproject"

    func main() {
      thc, err := gtoggl.NewClient("token")
      ...
      tc, err := gtproject.NewClient(thc)
      ...
      project,err := tc.Get(1)
      if err == nil {
        panic(err)
       }
    }
    ```
  description: "The gtoggl clients provides throttling"
examples:
  - "See [godoc][doc] for more examples"
tests:
  - |
    ```shell
    $ go test -v ./...

    ```
